version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 15672:15672
      # - 5672:5672 
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - saga-2-net

  service_orchestrator:
    image: saga-2-orchestrator
    depends_on:
      - rabbitmq
      - service_ticket
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks: [saga-2-net]





  service_ticket:
    image: saga-2-service-ticket
    depends_on:
      - rabbitmq
      - database_ticket
    ports:
      - 8090:8090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks: [saga-2-net, service-ticket-net]
  
  database_ticket:
    container_name: db_ticket
    restart: always
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ticket
      MYSQL_ROOT_PASSWORD: 123123
    networks: [service-ticket-net]

  

  service_room:
    image: saga-2-service-room
    depends_on:
      - rabbitmq
      - service_orchestrator
      - database_room
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks: [saga-2-net, service-room-net]

  database_room:
    container_name: db_room
    restart: always
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: room
      MYSQL_ROOT_PASSWORD: 123123
    networks: [service-room-net]


  service_account:
    image: saga-2-service-account
    depends_on:
      - rabbitmq
      - service_orchestrator
      - database_account
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks: [saga-2-net, service-account-net]

  database_account:
    container_name: db_account
    restart: always
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: 123123
    networks: [service-account-net]


networks:
  saga-2-net:
    driver: bridge
  service-ticket-net:
    driver: bridge
  service-room-net:
    driver: bridge
  service-account-net:
    driver: bridge

